### ISSUE TITLE
StutterJuice LV2 segfaults

### ISSUE THREAD

**Issue by trebmuh** [DISTRHO/JuicePlugins#4]
StutterJuice (build from https://github.com/DISTRHO/JuicePlugins/commit/3a2809dbdebfa20d0658ce02533cca43bbe0c713) is failing to start with `jalv -s urn:distrho:StutterJuice`. The terminal says:
```
$ jalv -s urn:distrho:StutterJuice
Plugin:       urn:distrho:StutterJuice
UI:           urn:distrho:StutterJuice#UI
JACK Name:    StutterJuice
Sample rate:  48000 Hz
Block length: 256 frames
MIDI buffers: 32768 bytes
Comm buffers: 32768 bytes
Update rate:  25.0 Hz

JACK Name:    StutterJuice
lv2_port_4      = 0.500000
lv2_port_5      = 0.500000
lv2_port_6      = 0.500000
lv2_port_7      = 0.500000
lv2_port_8      = 0.500000
lv2_port_9      = 0.500000
lv2_port_10     = 0.500000
lv2_port_11     = 0.500000
lv2_port_12     = 0.500000
lv2_port_13     = 0.500000
lv2_port_14     = 0.500000
lv2_port_15     = 0.500000
lv2_port_16     = 0.500000
lv2_port_17     = 0.500000
lv2_port_18     = 0.500000
lv2_port_19     = 0.500000
lv2_port_20     = 0.500000
lv2_port_21     = 0.500000
lv2_port_22     = 0.001852
lv2_port_23     = 0.000000
lv2_port_24     = 0.000000
lv2_port_25     = 0.000000
lv2_port_26     = 0.000000
lv2_port_27     = 0.000000
lv2_port_28     = 0.000000
lv2_port_29     = 0.000000
lv2_port_30     = 0.000000
lv2_port_31     = 0.000000
lv2_port_32     = 0.000000
lv2_port_33     = 0.000000
lv2_port_34     = 0.000000
lv2_port_35     = 0.000000
lv2_port_36     = 0.000000
lv2_port_37     = 0.000000
Erreur de segmentation
```
Nothing else. Note that "Erreur de segmentation" translates to "segfault".

Note that it is displaying itself as standalone, and in Carla as a LV2 and VST too. Moving the faders is working in the 2 first lines, but touching the faders of the last line (Delay, Break, and Detune), make it crashes in standalone, and is crashing Carla (RC2) in LV2.

Note also that using the VST2 in Carla is displaying a weird blue "Delay" square as shown here:

![stutter-carla-vst](https://user-images.githubusercontent.com/8705846/50378725-f3385000-0638-11e9-9925-06fedb7cc191.png)

Let me know if you need anything else.

**Comment by falkTX** [comment]
On a better look, StutterJuice plugin was never finished.
I have removed it from the default build now, closing as "wont-fix" since it is not my original plugin.

**Comment by trebmuh** [comment]
Sad-ish but understandable.
Thanks for the feedback.
